// City data for SEO-optimized local landing pages
// Each city targets "hair extensions [city]" + "wholesale hair extensions [city]" keywords

export interface CityData {
  slug: string
  name: string
  region: string
  country: string
  // SEO fields
  metaTitle: string
  metaDescription: string
  keywords: string[]
  // Content fields
  h1: string
  introParagraph: string
  deliveryTime: string
  distanceFromManchester: string
  popularMethods: string[]
  localSalonScene: string
  faqs: { question: string; answer: string }[]
}

export const cities: CityData[] = [
  {
    slug: 'manchester',
    name: 'Manchester',
    region: 'Greater Manchester',
    country: 'England',
    metaTitle: 'Hair Extensions Manchester | Wholesale Supplier for Salons | D.S Hair Beauty',
    metaDescription: 'Manchester\'s #1 wholesale hair extension supplier. 100% Remy human hair — tape-in, nano ring, K-tip, hand-tied weft, butterfly weft. Same-day dispatch. 19 years expertise. Trade accounts available.',
    keywords: [
      'hair extensions Manchester',
      'wholesale hair extensions Manchester',
      'hair extension supplier Manchester',
      'nano ring extensions Manchester',
      'tape-in extensions Manchester',
      'hand-tied weft Manchester',
      'balayage extensions Manchester',
      'salon hair supplier Manchester',
      'Remy hair extensions Manchester',
      'hair extension wholesale Manchester',
    ],
    h1: 'Hair Extensions Manchester — Wholesale Supplier for Professional Salons',
    introParagraph: 'D.S HAIR & BEAUTY is Manchester\'s leading wholesale hair extension supplier, providing 100% Remy human hair extensions to professional salons since 2007. Based in the heart of Manchester, we offer same-day dispatch and local collection for Greater Manchester salons, with factory-direct pricing on tape-in, nano ring, K-tip, hand-tied weft, butterfly weft, clip-in, and hair toppers.',
    deliveryTime: 'Same-day dispatch, local collection available',
    distanceFromManchester: '0 miles (headquarters)',
    popularMethods: ['Nano Ring', 'Hand-Tied Weft', 'Tape-In', 'Butterfly Weft'],
    localSalonScene: 'Manchester is one of the UK\'s fastest-growing hair extension markets, with over 1,200 registered hair salons in Greater Manchester. The city\'s vibrant beauty scene and competitive salon industry demand high-quality, reliable hair extension supply. D.S HAIR & BEAUTY has been serving Manchester salons since 2007, building deep relationships with local stylists who trust our factory-direct Remy hair for their clients.',
    faqs: [
      {
        question: 'Where can I buy wholesale hair extensions in Manchester?',
        answer: 'D.S HAIR & BEAUTY is Manchester\'s leading wholesale hair extension supplier, based in the city centre. We offer same-day dispatch and local collection for Greater Manchester salons. Open a trade account to access wholesale pricing on 100% Remy human hair extensions including tape-in, nano ring, K-tip, and hand-tied weft.',
      },
      {
        question: 'Do you offer same-day delivery for Manchester salons?',
        answer: 'Yes. As a Manchester-based supplier, we offer same-day dispatch for all orders placed before 2pm. Greater Manchester salons can also arrange local collection. This is a key advantage of choosing a local Manchester supplier over national distributors.',
      },
      {
        question: 'What hair extension methods are most popular in Manchester salons?',
        answer: 'Nano ring extensions and hand-tied weft are the most popular methods in Manchester, followed by tape-in and the increasingly popular butterfly weft. Manchester salons particularly favour balayage extensions, with over 70% of clients requesting balayage colour.',
      },
    ],
  },
  {
    slug: 'london',
    name: 'London',
    region: 'Greater London',
    country: 'England',
    metaTitle: 'Hair Extensions London | Wholesale Supplier for Salons | D.S Hair Beauty',
    metaDescription: 'Wholesale hair extensions for London salons. 100% Remy human hair — tape-in, nano ring, K-tip, weft, butterfly weft. Next-day delivery to London. Trade accounts with factory-direct pricing.',
    keywords: [
      'hair extensions London',
      'wholesale hair extensions London',
      'hair extension supplier London',
      'tape-in extensions London',
      'nano ring extensions London',
      'hand-tied weft London',
      'salon hair supplier London',
      'Remy hair extensions London',
      'hair extension wholesale London',
      'professional hair extensions London',
    ],
    h1: 'Hair Extensions London — Wholesale Remy Hair for Professional Salons',
    introParagraph: 'D.S HAIR & BEAUTY supplies 100% Remy human hair extensions at wholesale prices to professional salons across London. With next-day delivery to all London postcodes, we provide factory-direct pricing on tape-in, nano ring, K-tip, hand-tied weft, butterfly weft, and clip-in extensions. London salons trust our 19 years of industry expertise and consistent quality.',
    deliveryTime: 'Next-day delivery to all London postcodes',
    distanceFromManchester: '200 miles',
    popularMethods: ['Tape-In', 'K-Tip', 'Hand-Tied Weft', 'Nano Ring'],
    localSalonScene: 'London is the UK\'s largest hair extension market, with thousands of salons ranging from high-end Mayfair boutiques to busy high-street chains. London salons demand premium quality and reliable supply chains. D.S HAIR & BEAUTY serves London with next-day delivery, ensuring salons never run out of stock. Our factory-direct pricing gives London salons a competitive edge in a market where margins matter.',
    faqs: [
      {
        question: 'Can London salons get next-day delivery on hair extensions?',
        answer: 'Yes. D.S HAIR & BEAUTY offers next-day delivery to all London postcodes for orders placed before 2pm. Our Manchester warehouse dispatches same-day, ensuring London salons receive their hair extensions quickly and reliably.',
      },
      {
        question: 'Do you supply hair extensions to high-end London salons?',
        answer: 'Yes. Our 100% Remy human hair extensions are used by premium London salons that demand the highest quality. We supply tape-in, K-tip, nano ring, hand-tied weft, and butterfly weft extensions — all factory-direct with full quality guarantees.',
      },
      {
        question: 'What is the minimum order for London trade accounts?',
        answer: 'There is no minimum order for most products. London salons can order as little or as much as they need. Trade accounts receive wholesale pricing, priority stock access, and dedicated support.',
      },
    ],
  },
  {
    slug: 'birmingham',
    name: 'Birmingham',
    region: 'West Midlands',
    country: 'England',
    metaTitle: 'Hair Extensions Birmingham | Wholesale Supplier for Salons | D.S Hair Beauty',
    metaDescription: 'Wholesale hair extensions for Birmingham salons. 100% Remy human hair — tape-in, nano ring, K-tip, weft, butterfly weft. Next-day delivery. Trade accounts with factory-direct pricing.',
    keywords: [
      'hair extensions Birmingham',
      'wholesale hair extensions Birmingham',
      'hair extension supplier Birmingham',
      'tape-in extensions Birmingham',
      'nano ring extensions Birmingham',
      'hand-tied weft Birmingham',
      'salon hair supplier Birmingham',
      'Remy hair extensions Birmingham',
      'hair extension wholesale Birmingham',
    ],
    h1: 'Hair Extensions Birmingham — Wholesale Supplier for Professional Salons',
    introParagraph: 'D.S HAIR & BEAUTY supplies 100% Remy human hair extensions at wholesale prices to professional salons across Birmingham and the West Midlands. With next-day delivery, we provide factory-direct pricing on the full range of tape-in, nano ring, K-tip, hand-tied weft, and butterfly weft extensions. Birmingham salons benefit from our 19 years of expertise and reliable supply chain.',
    deliveryTime: 'Next-day delivery to all Birmingham postcodes',
    distanceFromManchester: '87 miles',
    popularMethods: ['Nano Ring', 'Tape-In', 'Weft', 'K-Tip'],
    localSalonScene: 'Birmingham is the UK\'s second-largest city with a thriving salon industry. The city\'s diverse population drives demand for a wide range of hair extension methods and colours. Birmingham salons particularly favour nano ring and tape-in extensions for their versatility across different hair types.',
    faqs: [
      {
        question: 'Where can Birmingham salons buy wholesale hair extensions?',
        answer: 'D.S HAIR & BEAUTY supplies wholesale hair extensions to Birmingham salons with next-day delivery. We offer 100% Remy human hair extensions including tape-in, nano ring, K-tip, and weft at factory-direct prices. Open a trade account for wholesale pricing.',
      },
      {
        question: 'How fast is delivery to Birmingham?',
        answer: 'Next-day delivery to all Birmingham postcodes for orders placed before 2pm. Our Manchester warehouse dispatches same-day, ensuring Birmingham salons receive their extensions quickly.',
      },
    ],
  },
  {
    slug: 'liverpool',
    name: 'Liverpool',
    region: 'Merseyside',
    country: 'England',
    metaTitle: 'Hair Extensions Liverpool | Wholesale Supplier for Salons | D.S Hair Beauty',
    metaDescription: 'Wholesale hair extensions for Liverpool salons. 100% Remy human hair — tape-in, nano ring, K-tip, weft, butterfly weft. Next-day delivery. Trade accounts with factory-direct pricing.',
    keywords: [
      'hair extensions Liverpool',
      'wholesale hair extensions Liverpool',
      'hair extension supplier Liverpool',
      'tape-in extensions Liverpool',
      'nano ring extensions Liverpool',
      'hand-tied weft Liverpool',
      'salon hair supplier Liverpool',
      'Remy hair extensions Liverpool',
      'hair extension wholesale Liverpool',
    ],
    h1: 'Hair Extensions Liverpool — Wholesale Supplier for Professional Salons',
    introParagraph: 'D.S HAIR & BEAUTY supplies 100% Remy human hair extensions at wholesale prices to professional salons across Liverpool and Merseyside. With next-day delivery, we provide factory-direct pricing on tape-in, nano ring, K-tip, hand-tied weft, and butterfly weft extensions. Liverpool salons trust our consistent quality and 19 years of industry expertise.',
    deliveryTime: 'Next-day delivery to all Liverpool postcodes',
    distanceFromManchester: '35 miles',
    popularMethods: ['Nano Ring', 'Tape-In', 'Weft', 'Clip-In'],
    localSalonScene: 'Liverpool has a vibrant beauty and hair industry, with salons known for bold, fashion-forward styles. The city\'s competitive salon market demands high-quality extensions at competitive prices. Liverpool salons particularly favour nano ring extensions for their invisible finish and hand-tied weft for maximum volume.',
    faqs: [
      {
        question: 'Where can Liverpool salons buy wholesale hair extensions?',
        answer: 'D.S HAIR & BEAUTY supplies wholesale 100% Remy human hair extensions to Liverpool salons with next-day delivery. Open a trade account for factory-direct pricing on tape-in, nano ring, K-tip, and weft extensions.',
      },
      {
        question: 'How fast is delivery to Liverpool?',
        answer: 'Next-day delivery to all Liverpool postcodes for orders placed before 2pm. Being only 35 miles from Manchester, Liverpool salons often receive deliveries even faster.',
      },
    ],
  },
  {
    slug: 'leeds',
    name: 'Leeds',
    region: 'West Yorkshire',
    country: 'England',
    metaTitle: 'Hair Extensions Leeds | Wholesale Supplier for Salons | D.S Hair Beauty',
    metaDescription: 'Wholesale hair extensions for Leeds salons. 100% Remy human hair — tape-in, nano ring, K-tip, weft, butterfly weft. Next-day delivery. Trade accounts with factory-direct pricing.',
    keywords: [
      'hair extensions Leeds',
      'wholesale hair extensions Leeds',
      'hair extension supplier Leeds',
      'tape-in extensions Leeds',
      'nano ring extensions Leeds',
      'hand-tied weft Leeds',
      'salon hair supplier Leeds',
      'Remy hair extensions Leeds',
      'hair extension wholesale Leeds',
    ],
    h1: 'Hair Extensions Leeds — Wholesale Supplier for Professional Salons',
    introParagraph: 'D.S HAIR & BEAUTY supplies 100% Remy human hair extensions at wholesale prices to professional salons across Leeds and West Yorkshire. With next-day delivery, we provide factory-direct pricing on tape-in, nano ring, K-tip, hand-tied weft, and butterfly weft extensions. Leeds salons benefit from our reliable supply chain and 19 years of expertise.',
    deliveryTime: 'Next-day delivery to all Leeds postcodes',
    distanceFromManchester: '45 miles',
    popularMethods: ['Tape-In', 'Hand-Tied Weft', 'Nano Ring', 'K-Tip'],
    localSalonScene: 'Leeds is one of Yorkshire\'s largest salon markets, with a growing demand for premium hair extensions. The city\'s fashion-conscious clientele drives demand for balayage extensions and natural-looking methods like nano ring and hand-tied weft.',
    faqs: [
      {
        question: 'Where can Leeds salons buy wholesale hair extensions?',
        answer: 'D.S HAIR & BEAUTY supplies wholesale 100% Remy human hair extensions to Leeds salons with next-day delivery. Trade accounts get factory-direct pricing on tape-in, nano ring, K-tip, weft, and butterfly weft extensions.',
      },
    ],
  },
  {
    slug: 'sheffield',
    name: 'Sheffield',
    region: 'South Yorkshire',
    country: 'England',
    metaTitle: 'Hair Extensions Sheffield | Wholesale Supplier for Salons | D.S Hair Beauty',
    metaDescription: 'Wholesale hair extensions for Sheffield salons. 100% Remy human hair — tape-in, nano ring, K-tip, weft, butterfly weft. Next-day delivery. Trade accounts with factory-direct pricing.',
    keywords: [
      'hair extensions Sheffield',
      'wholesale hair extensions Sheffield',
      'hair extension supplier Sheffield',
      'tape-in extensions Sheffield',
      'nano ring extensions Sheffield',
      'salon hair supplier Sheffield',
      'Remy hair extensions Sheffield',
      'hair extension wholesale Sheffield',
    ],
    h1: 'Hair Extensions Sheffield — Wholesale Supplier for Professional Salons',
    introParagraph: 'D.S HAIR & BEAUTY supplies 100% Remy human hair extensions at wholesale prices to professional salons across Sheffield and South Yorkshire. With next-day delivery, we provide factory-direct pricing on the full range of extension methods. Sheffield salons trust our consistent quality and 19 years of industry expertise.',
    deliveryTime: 'Next-day delivery to all Sheffield postcodes',
    distanceFromManchester: '38 miles',
    popularMethods: ['Nano Ring', 'Tape-In', 'Weft', 'K-Tip'],
    localSalonScene: 'Sheffield has a growing hair extension market with salons serving both urban and suburban clientele. The city\'s salons demand reliable supply and competitive pricing, making D.S HAIR & BEAUTY\'s factory-direct model particularly attractive.',
    faqs: [
      {
        question: 'Where can Sheffield salons buy wholesale hair extensions?',
        answer: 'D.S HAIR & BEAUTY supplies wholesale 100% Remy human hair extensions to Sheffield salons with next-day delivery. Open a trade account for factory-direct pricing.',
      },
    ],
  },
  {
    slug: 'bristol',
    name: 'Bristol',
    region: 'South West England',
    country: 'England',
    metaTitle: 'Hair Extensions Bristol | Wholesale Supplier for Salons | D.S Hair Beauty',
    metaDescription: 'Wholesale hair extensions for Bristol salons. 100% Remy human hair — tape-in, nano ring, K-tip, weft, butterfly weft. Next-day delivery. Trade accounts with factory-direct pricing.',
    keywords: [
      'hair extensions Bristol',
      'wholesale hair extensions Bristol',
      'hair extension supplier Bristol',
      'tape-in extensions Bristol',
      'nano ring extensions Bristol',
      'salon hair supplier Bristol',
      'Remy hair extensions Bristol',
      'hair extension wholesale Bristol',
    ],
    h1: 'Hair Extensions Bristol — Wholesale Supplier for Professional Salons',
    introParagraph: 'D.S HAIR & BEAUTY supplies 100% Remy human hair extensions at wholesale prices to professional salons across Bristol and the South West. With next-day delivery, we provide factory-direct pricing on tape-in, nano ring, K-tip, hand-tied weft, and butterfly weft extensions. Bristol salons benefit from our reliable supply and 19 years of expertise.',
    deliveryTime: 'Next-day delivery to all Bristol postcodes',
    distanceFromManchester: '165 miles',
    popularMethods: ['Tape-In', 'Nano Ring', 'K-Tip', 'Hand-Tied Weft'],
    localSalonScene: 'Bristol has a creative, trend-setting salon scene that embraces new extension methods. The city\'s salons are early adopters of butterfly weft and nano ring extensions, and demand high-quality Remy hair for their fashion-forward clientele.',
    faqs: [
      {
        question: 'Where can Bristol salons buy wholesale hair extensions?',
        answer: 'D.S HAIR & BEAUTY supplies wholesale 100% Remy human hair extensions to Bristol salons with next-day delivery. Trade accounts get factory-direct pricing on all extension methods.',
      },
    ],
  },
  {
    slug: 'edinburgh',
    name: 'Edinburgh',
    region: 'Scotland',
    country: 'Scotland',
    metaTitle: 'Hair Extensions Edinburgh | Wholesale Supplier for Salons | D.S Hair Beauty',
    metaDescription: 'Wholesale hair extensions for Edinburgh salons. 100% Remy human hair — tape-in, nano ring, K-tip, weft, butterfly weft. 1-2 day delivery. Trade accounts with factory-direct pricing.',
    keywords: [
      'hair extensions Edinburgh',
      'wholesale hair extensions Edinburgh',
      'hair extension supplier Edinburgh',
      'tape-in extensions Edinburgh',
      'nano ring extensions Edinburgh',
      'salon hair supplier Edinburgh',
      'Remy hair extensions Edinburgh',
      'hair extension wholesale Edinburgh',
    ],
    h1: 'Hair Extensions Edinburgh — Wholesale Supplier for Professional Salons',
    introParagraph: 'D.S HAIR & BEAUTY supplies 100% Remy human hair extensions at wholesale prices to professional salons across Edinburgh and Scotland. With 1-2 day delivery, we provide factory-direct pricing on tape-in, nano ring, K-tip, hand-tied weft, and butterfly weft extensions. Edinburgh salons trust our consistent quality and 19 years of industry expertise.',
    deliveryTime: '1-2 day delivery to all Edinburgh postcodes',
    distanceFromManchester: '220 miles',
    popularMethods: ['Nano Ring', 'Tape-In', 'K-Tip', 'Hand-Tied Weft'],
    localSalonScene: 'Edinburgh\'s premium salon market demands high-quality extensions for a discerning clientele. The city\'s salons particularly favour nano ring and K-tip extensions for their natural, long-lasting results. D.S HAIR & BEAUTY provides Edinburgh salons with factory-direct Remy hair at competitive wholesale prices.',
    faqs: [
      {
        question: 'Where can Edinburgh salons buy wholesale hair extensions?',
        answer: 'D.S HAIR & BEAUTY supplies wholesale 100% Remy human hair extensions to Edinburgh salons with 1-2 day delivery. Trade accounts get factory-direct pricing on all extension methods.',
      },
    ],
  },
  {
    slug: 'glasgow',
    name: 'Glasgow',
    region: 'Scotland',
    country: 'Scotland',
    metaTitle: 'Hair Extensions Glasgow | Wholesale Supplier for Salons | D.S Hair Beauty',
    metaDescription: 'Wholesale hair extensions for Glasgow salons. 100% Remy human hair — tape-in, nano ring, K-tip, weft, butterfly weft. 1-2 day delivery. Trade accounts with factory-direct pricing.',
    keywords: [
      'hair extensions Glasgow',
      'wholesale hair extensions Glasgow',
      'hair extension supplier Glasgow',
      'tape-in extensions Glasgow',
      'nano ring extensions Glasgow',
      'salon hair supplier Glasgow',
      'Remy hair extensions Glasgow',
      'hair extension wholesale Glasgow',
    ],
    h1: 'Hair Extensions Glasgow — Wholesale Supplier for Professional Salons',
    introParagraph: 'D.S HAIR & BEAUTY supplies 100% Remy human hair extensions at wholesale prices to professional salons across Glasgow and Scotland. With 1-2 day delivery, we provide factory-direct pricing on tape-in, nano ring, K-tip, hand-tied weft, and butterfly weft extensions. Glasgow salons trust our consistent quality and 19 years of industry expertise.',
    deliveryTime: '1-2 day delivery to all Glasgow postcodes',
    distanceFromManchester: '215 miles',
    popularMethods: ['Tape-In', 'Nano Ring', 'Weft', 'K-Tip'],
    localSalonScene: 'Glasgow has Scotland\'s largest salon market, with a high demand for hair extensions across all methods. The city\'s salons serve a diverse clientele and require reliable supply of multiple extension types and colours. D.S HAIR & BEAUTY provides Glasgow salons with factory-direct Remy hair at competitive wholesale prices.',
    faqs: [
      {
        question: 'Where can Glasgow salons buy wholesale hair extensions?',
        answer: 'D.S HAIR & BEAUTY supplies wholesale 100% Remy human hair extensions to Glasgow salons with 1-2 day delivery. Trade accounts get factory-direct pricing on all extension methods.',
      },
    ],
  },
  {
    slug: 'cardiff',
    name: 'Cardiff',
    region: 'Wales',
    country: 'Wales',
    metaTitle: 'Hair Extensions Cardiff | Wholesale Supplier for Salons | D.S Hair Beauty',
    metaDescription: 'Wholesale hair extensions for Cardiff salons. 100% Remy human hair — tape-in, nano ring, K-tip, weft, butterfly weft. 1-2 day delivery. Trade accounts with factory-direct pricing.',
    keywords: [
      'hair extensions Cardiff',
      'wholesale hair extensions Cardiff',
      'hair extension supplier Cardiff',
      'tape-in extensions Cardiff',
      'nano ring extensions Cardiff',
      'salon hair supplier Cardiff',
      'Remy hair extensions Cardiff',
      'hair extension wholesale Cardiff',
    ],
    h1: 'Hair Extensions Cardiff — Wholesale Supplier for Professional Salons',
    introParagraph: 'D.S HAIR & BEAUTY supplies 100% Remy human hair extensions at wholesale prices to professional salons across Cardiff and Wales. With 1-2 day delivery, we provide factory-direct pricing on tape-in, nano ring, K-tip, hand-tied weft, and butterfly weft extensions. Cardiff salons benefit from our reliable supply chain and 19 years of expertise.',
    deliveryTime: '1-2 day delivery to all Cardiff postcodes',
    distanceFromManchester: '190 miles',
    popularMethods: ['Nano Ring', 'Tape-In', 'K-Tip', 'Weft'],
    localSalonScene: 'Cardiff is Wales\'s largest salon market, with a growing demand for premium hair extensions. The city\'s salons serve both urban and rural Welsh clientele, requiring versatile extension methods and reliable colour matching.',
    faqs: [
      {
        question: 'Where can Cardiff salons buy wholesale hair extensions?',
        answer: 'D.S HAIR & BEAUTY supplies wholesale 100% Remy human hair extensions to Cardiff salons with 1-2 day delivery. Trade accounts get factory-direct pricing on all extension methods.',
      },
    ],
  },
  {
    slug: 'nottingham',
    name: 'Nottingham',
    region: 'East Midlands',
    country: 'England',
    metaTitle: 'Hair Extensions Nottingham | Wholesale Supplier for Salons | D.S Hair Beauty',
    metaDescription: 'Wholesale hair extensions for Nottingham salons. 100% Remy human hair — tape-in, nano ring, K-tip, weft, butterfly weft. Next-day delivery. Trade accounts with factory-direct pricing.',
    keywords: [
      'hair extensions Nottingham',
      'wholesale hair extensions Nottingham',
      'hair extension supplier Nottingham',
      'tape-in extensions Nottingham',
      'nano ring extensions Nottingham',
      'salon hair supplier Nottingham',
      'Remy hair extensions Nottingham',
      'hair extension wholesale Nottingham',
    ],
    h1: 'Hair Extensions Nottingham — Wholesale Supplier for Professional Salons',
    introParagraph: 'D.S HAIR & BEAUTY supplies 100% Remy human hair extensions at wholesale prices to professional salons across Nottingham and the East Midlands. With next-day delivery, we provide factory-direct pricing on tape-in, nano ring, K-tip, hand-tied weft, and butterfly weft extensions. Nottingham salons trust our consistent quality and 19 years of expertise.',
    deliveryTime: 'Next-day delivery to all Nottingham postcodes',
    distanceFromManchester: '75 miles',
    popularMethods: ['Tape-In', 'Nano Ring', 'Weft', 'K-Tip'],
    localSalonScene: 'Nottingham has a competitive salon market with strong demand for hair extensions. The city\'s salons serve a young, fashion-conscious demographic that drives demand for the latest extension methods including butterfly weft and nano ring.',
    faqs: [
      {
        question: 'Where can Nottingham salons buy wholesale hair extensions?',
        answer: 'D.S HAIR & BEAUTY supplies wholesale 100% Remy human hair extensions to Nottingham salons with next-day delivery. Trade accounts get factory-direct pricing.',
      },
    ],
  },
  {
    slug: 'newcastle',
    name: 'Newcastle',
    region: 'Tyne and Wear',
    country: 'England',
    metaTitle: 'Hair Extensions Newcastle | Wholesale Supplier for Salons | D.S Hair Beauty',
    metaDescription: 'Wholesale hair extensions for Newcastle salons. 100% Remy human hair — tape-in, nano ring, K-tip, weft, butterfly weft. Next-day delivery. Trade accounts with factory-direct pricing.',
    keywords: [
      'hair extensions Newcastle',
      'wholesale hair extensions Newcastle',
      'hair extension supplier Newcastle',
      'tape-in extensions Newcastle',
      'nano ring extensions Newcastle',
      'salon hair supplier Newcastle',
      'Remy hair extensions Newcastle',
      'hair extension wholesale Newcastle',
    ],
    h1: 'Hair Extensions Newcastle — Wholesale Supplier for Professional Salons',
    introParagraph: 'D.S HAIR & BEAUTY supplies 100% Remy human hair extensions at wholesale prices to professional salons across Newcastle and the North East. With next-day delivery, we provide factory-direct pricing on tape-in, nano ring, K-tip, hand-tied weft, and butterfly weft extensions. Newcastle salons trust our consistent quality and 19 years of expertise.',
    deliveryTime: 'Next-day delivery to all Newcastle postcodes',
    distanceFromManchester: '140 miles',
    popularMethods: ['Nano Ring', 'Tape-In', 'K-Tip', 'Weft'],
    localSalonScene: 'Newcastle has a strong beauty industry with salons known for glamorous, bold styles. The city\'s salons demand high-volume extensions and reliable supply. D.S HAIR & BEAUTY provides Newcastle salons with factory-direct Remy hair at competitive wholesale prices.',
    faqs: [
      {
        question: 'Where can Newcastle salons buy wholesale hair extensions?',
        answer: 'D.S HAIR & BEAUTY supplies wholesale 100% Remy human hair extensions to Newcastle salons with next-day delivery. Trade accounts get factory-direct pricing on all extension methods.',
      },
    ],
  },
]

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((city) => city.slug === slug)
}
